### ISSUE TITLE
rustlings panicking when updating exercise files

### ISSUE THREAD

**Issue by thenorili** [rust-lang/rustlings#1689]
I worked through many exercises over the course of three sessions without trouble using VSCode on Windows. When I got to struct 2 and saved the file, rustlings panicked with the following error message.

```
thread 'main' panicked at 'We were unable to open the exercise file!: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }', src\exercise.rs:205:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace */
```

This now happens consistently, including after restarting the terminal and VSCode. Since a new 'rustlings watch' checks all previous exercises, it's now very slow going.

Here's the full backtrace.

```
stack backtrace:
   0:     0x7ff7523e81cc - std::sys_common::backtrace::_print::impl$0::fmt
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\sys_common\backtrace.rs:44
   1:     0x7ff75240b2cb - core::fmt::rt::Argument::fmt
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\fmt\rt.rs:138
   2:     0x7ff75240b2cb - core::fmt::write
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\fmt\mod.rs:1094
   3:     0x7ff7523e2dbf - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\io\mod.rs:1714
   4:     0x7ff7523e7f7b - std::sys_common::backtrace::_print
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\sys_common\backtrace.rs:47
   5:     0x7ff7523e7f7b - std::sys_common::backtrace::print
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\sys_common\backtrace.rs:34
   6:     0x7ff7523eaa4a - std::panicking::default_hook::closure$1
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:269
   7:     0x7ff7523ea69f - std::panicking::default_hook
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:288
   8:     0x7ff7523eb0fe - std::panicking::rust_panic_with_hook
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:705
   9:     0x7ff7523eafed - std::panicking::begin_panic_handler::closure$0
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:597
  10:     0x7ff7523e8e19 - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure_env$0,never$>
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\sys_common\backtrace.rs:151
  11:     0x7ff7523eacf0 - std::panicking::begin_panic_handler
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:593
  12:     0x7ff75241aed5 - core::panicking::panic_fmt
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\panicking.rs:67
  13:     0x7ff75241b3e3 - core::result::unwrap_failed
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\core\src\result.rs:1651
  14:     0x7ff75223479a - rustlings::exercise::Exercise::state::h0d1d09085db5ad3e
  15:     0x7ff7521f609b - <alloc::boxed::Box<T,A> as core::ops::drop::Drop>::drop::h88de01a6d1744faa
  16:     0x7ff752239476 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3e5f642e1d6437c4
  17:     0x7ff752224e4c - std::rt::lang_start::{{closure}}::h3e675a64d3ed7664
  18:     0x7ff7523db7c8 - std::rt::lang_start_internal::closure$2
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\rt.rs:148
  19:     0x7ff7523db7c8 - std::panicking::try::do_call
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:500
  20:     0x7ff7523db7c8 - std::panicking::try
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panicking.rs:464
  21:     0x7ff7523db7c8 - std::panic::catch_unwind
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\panic.rs:142
  22:     0x7ff7523db7c8 - std::rt::lang_start_internal
                               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library\std\src\rt.rs:148
  23:     0x7ff7522012fc - main
  24:     0x7ff75241283c - invoke_main
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
  25:     0x7ff75241283c - __scrt_common_main_seh
                               at D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
  26:     0x7ffcbb5a257d - BaseThreadInitThunk
  27:     0x7ffcbb92aa68 - RtlUserThreadStart
  ```

**Comment by thenorili** [comment]
It turns out that I accidentally dragged the error_handling folder into the functions folder and that caused this problem, now it's fixed.

**Comment by thenorili** [comment]
This has been broken into more meaningful tickets now
