### ISSUE TITLE
Devcontainer image might be outdated

### ISSUE THREAD

**Issue by SharathHuddar** [rust-lang/rustlings#1943]
I tried to run the project in a dev container and ran into this issue:
```59 ms] Dev Containers 0.354.0 in VS Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6).
[59 ms] Start: Resolving Remote
[66 ms] Initializing configuration support...
[66 ms] Internal initialization of dev container support package...
[114 ms] Setting up container for folder or workspace: /Users/sharath/workspace/learnings/rust_lang/rustlings
[115 ms] Start: Check Docker is running
[115 ms] Start: Run: docker version
[176 ms] Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.16.1 (95567)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
[182 ms] Start: Run: docker volume ls -q
[273 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/sharath/workspace/learnings/rust_lang/rustlings --filter label=vsch.quality=stable
[320 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings --filter label=devcontainer.config_file=/Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json
[370 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings
[424 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings
[476 ms] Running Dev Containers CLI:   read-configuration --workspace-folder /Users/sharath/workspace/learnings/rust_lang/rustlings --id-label devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings --id-label devcontainer.config_file=/Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --mount-workspace-git-root
[490 ms] ProxyResolver#loadSystemCertificates count
[491 ms] ProxyResolver#loadSystemCertificates count filtered
[491 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/sharath/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js read-configuration --workspace-folder /Users/sharath/workspace/learnings/rust_lang/rustlings --id-label devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings --id-label devcontainer.config_file=/Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --mount-workspace-git-root
[646 ms] @devcontainers/cli 0.58.0. Node.js v18.17.1. darwin 23.4.0 arm64.
[646 ms] Start: Run: git rev-parse --show-cdup
[653 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings --filter label=devcontainer.config_file=/Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json
[713 ms] Running Dev Containers CLI:   up --user-data-folder /Users/sharath/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-ed983e16-943f-4fdb-8671-f50fb3a602431712557212179 --workspace-folder /Users/sharath/workspace/learnings/rust_lang/rustlings --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings --id-label devcontainer.config_file=/Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[714 ms] Start: Run: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/sharath/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/sharath/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-ed983e16-943f-4fdb-8671-f50fb3a602431712557212179 --workspace-folder /Users/sharath/workspace/learnings/rust_lang/rustlings --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings --id-label devcontainer.config_file=/Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[873 ms] @devcontainers/cli 0.58.0. Node.js v18.17.1. darwin 23.4.0 arm64.
[873 ms] Start: Run: docker buildx version
[1024 ms] github.com/docker/buildx v0.10.0 876462897612d36679153c3414f7689626251501
[1024 ms] 
[1025 ms] Start: Resolving Remote
[1026 ms] Start: Run: git rev-parse --show-cdup
[1033 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings --filter label=devcontainer.config_file=/Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json
[1083 ms] Start: Run: docker inspect --type image mcr.microsoft.com/devcontainers/universal:2-linux
[1133 ms] Loading 3 extra certificates from /var/folders/ml/qfm109jd3gx9mwghvxb8x6z40000gn/T/vsch/certificates-c786cc9d734261bdec1dda89269c221d1075e29c2f079ebd918cf0075af032e5.pem.
[1675 ms] Error fetching image details: No manifest found for mcr.microsoft.com/devcontainers/universal:2-linux.
[1676 ms] Start: Run: docker pull mcr.microsoft.com/devcontainers/universal:2-linux
2-linux: Pulling from devcontainers/universal
no matching manifest for linux/arm64/v8 in the manifest list entries
[7925 ms] []
[7925 ms] Error: No such image: mcr.microsoft.com/devcontainers/universal:2-linux

[7926 ms] Error: Command failed: docker inspect --type image mcr.microsoft.com/devcontainers/universal:2-linux
[7926 ms]     at htA (/Users/sharath/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:464:1260)
[7926 ms]     at kH (/Users/sharath/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:464:1002)
[7929 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[7929 ms]     at async UtA (/Users/sharath/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:481:3692)
[7929 ms]     at async $C (/Users/sharath/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:481:4807)
[7929 ms]     at async QrA (/Users/sharath/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:661:13255)
[7929 ms]     at async urA (/Users/sharath/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js:661:12996)
[7933 ms] Exit code 1
[7936 ms] Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) /Users/sharath/.vscode/extensions/ms-vscode-remote.remote-containers-0.354.0/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /Users/sharath/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-containers/data --container-session-data-folder /tmp/devcontainers-ed983e16-943f-4fdb-8671-f50fb3a602431712557212179 --workspace-folder /Users/sharath/workspace/learnings/rust_lang/rustlings --workspace-mount-consistency cached --id-label devcontainer.local_folder=/Users/sharath/workspace/learnings/rust_lang/rustlings --id-label devcontainer.config_file=/Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --log-level debug --log-format json --config /Users/sharath/workspace/learnings/rust_lang/rustlings/.devcontainer/devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root
[7936 ms] Exit code 1
```

Looks like the docker image does not exist anymore. 
I can raise a PR to fix this if someone can help me identify the right image for this project

**Comment by SharathHuddar** [comment]
Looks like the container has already been updated on main branch. I ran into this issue since I used the install.sh script which checks out to the latest release which does not have the updated container image. Creating a new release should fix this issue

**Comment by mo8it** [comment]
Thanks for the report. A new version will be released in about 2 weeks, but it will remove the whole devcontainer because of the new installation method (see the changelog after the release).
I suggest using the normal Rustlings installation method or the devcontainer from the main branch until version 6 is released :)
